name: Tox tests

on: [push, pull_request]

jobs:
  py38:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install OS packages
        run: |
          sudo apt-get -y update
          sudo apt-get install -y rpm libkrb5-dev
      - name: Upgrade pip
        run: pip install --upgrade pip
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py38
  py312:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.12"
      - name: Install base packages
        run: sudo apt-get install gcc python3-dev libkrb5-dev
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e py312
  static:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install OS packages
        run: |
          sudo apt-get -y update
          sudo apt-get install -y rpm libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e static
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install OS packages
        run: |
          sudo apt-get -y update
          sudo apt-get install -y rpm libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Tox
        run: pip install tox
      - name: Install pytest cov
        run: pip install pytest-cov
      - name: Run Tox
        run: tox -e cov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          fail_ci_if_error: true
          verbose: true
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install OS packages
        run: |
          sudo apt-get -y update
          sudo apt-get install -y rpm libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e docs
  bandit-exitzero:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install OS packages
        run: |
          sudo apt-get -y update
          sudo apt-get install -y rpm
          sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e bandit-exitzero
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install OS packages
        run: |
          sudo apt-get -y update
          sudo apt-get install -y rpm
          sudo apt-get install -y libkrb5-dev
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Tox
        run: pip install tox
      - name: Run Tox
        run: tox -e bandit
